### Get the list of orders

GET http://localhost:5000/orders
Accept: application/json

### Send alert that order is in delivered state

GET http://localhost:5000/alert
Accept: application/json

### Update the order

GET http://localhost:5000/update
Accept: application/json